Update README.md
sfeir-open-source/sfeir-school-theme pull request #98
Opened 2023-03-09 08:49 UTC by shepard8

Fixes #86

2023-03-09 16:15 UTC, jefBinomed requested changes
La correction ne correspond pas du coup

2023-03-09 16:15 UTC, jefBinomed commented on README.md
> +-   `full-height`: enhanced the size of code block to the maximum of the screen
Alors, en fait c'est bien max-height si tu regarde le code de la démo, c'est juste qu'il faut préciser que le max-height est à mettre au niveau de la section et pas sous le block de code... de plus, le code de la démo (celui qui montre comment faire) n'est pas à jour non plus -> CF Ligne 50 du fichier markdown 30_code_slides.md

2023-03-10 09:08 UTC, shepard8 commented on README.md
> +-   `full-height`: enhanced the size of code block to the maximum of the screen
J'ai fixé tout ça :)

2023-03-17 15:19 UTC, jefBinomed requested changes
Désolé, je te demande encore des petites modifs

2023-03-17 15:19 UTC, jefBinomed commented on README.md
> +    The additional class `alone` will position the code in the center of screen instead of relative to its parent.
je vais faire mon relou sur cette PR mais en fait, ne positionne pas la remarque sur le `alone` juste avant l'image car ça peut être confusant. Je trouve que son emplacement après  était bien placé car ça concernait une sous spécificité du code. Ou alors on fait un screenshot du cas `alone`

2023-03-17 15:19 UTC, jefBinomed commented on README.md
> +    _Note: the slide should contain only a code block to avoid an overflow._
pas forcément en vrai, c'est juste que ça étend le max-height autorisé donc c'est pas une contrainte.

2023-03-17 15:19 UTC, jefBinomed commented on README.md
> +-   `max-height`: make the code block of the slide take all vertical space
je préciserais 'this class should be define on the second as a complement of with-code or with-code-dark classes'. Et là on est précis dans le fonctionnement

2023-07-05 15:24 UTC, merged